USE [RUL-WRS]
GO

IF OBJECT_ID('dbo.IOT_GATEWAY') IS NULL
	CREATE TABLE dbo.IOT_GATEWAY
	(
		FECHA_HORA DATETIME,
		ID_MAQUINA VARCHAR(10),
		TIPO_MAQUINA VARCHAR(8),
		CARGA_CUCHARON INT,
		CARGA_ACTUAL_CAMION INT,
		CARGA_ULTIMO_CAMION INT,
		TONELADAS_TURNO BIGINT,
		VOLTAJE_LINEA NUMERIC(12,8),
		POTENCIA_KW_MOVIMIENTOS SMALLINT,
		FACTOR_POTENCIA SMALLINT,
		POTENCIA_KW_MAQUINA SMALLINT,
		TEMP_TRANSFORMADOR_1 SMALLINT,
		TEMP_TRANSFORMADOR_2 SMALLINT,
		VELOCIDAD_HOIST SMALLINT,
		TORQUE_HOIST SMALLINT,
		CORRIENTE_IW_HOIST SMALLINT,
		POTENCIA_KW_HOIST SMALLINT,
		VEL_REF_HOIST SMALLINT,
		TEMP_MOTOR_HOIST SMALLINT,
		EXTENSION_CROWD NUMERIC(12,8),
		LONGITUD_CABLE_HOIST NUMERIC(12,8),
		ANGULO_SWING SMALLINT,
		TEMP_MOD_IGBT_1 SMALLINT,
		TEMP_MOD_IGBT_2 SMALLINT,
		TEMP_MOD_IGBT_3 SMALLINT,
		TEMP_MOD_IGBT_4 SMALLINT,
		TEMP_MOD_IGBT_5 SMALLINT,
		TEMP_MOD_IGBT_6 SMALLINT,
		TEMP_MOD_IGBT_7 SMALLINT,
		TEMP_ROD_RH_TAMBOR_HOIST SMALLINT,
		TEMP_ROD_LH_TAMBOR_HOIST SMALLINT,
		TEMP_ROD_PIÑON_ENT_SUP_HOIST SMALLINT,
		TEMP_ROD_PIÑON_ENT_INF_HOIST SMALLINT,
		TEMP_ROD_RH_MOTOR_HOIST SMALLINT,
		TEMP_ROD_LH_MOTOR_HOIST SMALLINT,
		TEMP_ACEITE_TX_HOIST SMALLINT,
		PRESION_ACEITE_TX_HOIST SMALLINT,
		VELOCIDAD_CROWD SMALLINT,
		TORQUE_CROWD SMALLINT,
		CORRIENTE_IW_CROWD SMALLINT,
		POTENCIA_KW_CROWD SMALLINT,
		VEL_REFERENCIA_CROWD SMALLINT,
		TEMP_MOTOR_CROWD SMALLINT,
		TEMP_MOD_IGBT_8 SMALLINT,
		TEMP_MOD_IGBT_9 SMALLINT,
		TEMP_MOD_IGBT_10 SMALLINT,
		TEMP_MOD_IGBT_11 SMALLINT,
		TEMP_MOD_IGBT_12 SMALLINT,
		TEMP_MOD_CHOPPER_1 SMALLINT,
		TEMP_MOD_CHOPPER_2 SMALLINT,
		ANGULO_BETA NUMERIC(12,8),
		TEMP_ROD_RH_TAMBOR_CROWD SMALLINT,
		TEMP_ROD_LH_TAMBOR_CROWD SMALLINT,
		TEMP_ROD_INT_EJE_INGR_CROWD SMALLINT,
		TEMP_ROD_EXT_EJE_INGR_CROWD SMALLINT,
		TEMP_ROD_INT_EJE_INTER_1_CROWD SMALLINT,
		TEMP_ROD_EXT_EJE_INTER_1_CROWD SMALLINT,
		TEMP_ROD_INT_EJE_INTER_2_CROWD SMALLINT,
		TEMP_ROD_EXT_EJE_INTER_2_CROWD SMALLINT,
		TEMP_ROD_RH_MOTOR_CROWD SMALLINT,
		TEMP_ROD_LH_MOTOR_CROWD SMALLINT,
		VELOCIDAD_SWING SMALLINT,
		TORQUE_SWING SMALLINT,
		CORRIENTE_IW_SWING SMALLINT,
		POTENCIA_KW_SWING SMALLINT,
		REF_JOYSTICK_SWING SMALLINT,
		TEMP_MOTOR_SWING_1 SMALLINT,
		TEMP_MOTOR_SWING_2 SMALLINT,
		INCLINACION_TOTAL NUMERIC(12,8),
		INCLINACION_DEL_POST NUMERIC(12,8),
		INCLINACION_LADO_LADO NUMERIC(12,8),
		ANGULO_GIRO_CICLO SMALLINT,
		TEMP_AIRE_AMB_EXTERIOR SMALLINT,
		TEMP_AIRE_AMB_INTERIOR SMALLINT,
		TEMP_ROD_FRO_SUP_TX_SWING_1 SMALLINT,
		TEMP_ROD_POST_INF_TX_SWING_1 SMALLINT,
		TEMP_ROD_SUP_MOTOR_SWING_1 SMALLINT,
		TEMP_ROD_INF_TX_SWING_1 SMALLINT,
		PRESION_AIRE SMALLINT,
		PRESION_LUBRICACION_A1 SMALLINT,
		PRESION_LUBRICACION_A2 SMALLINT,
		PRESION_LUBRICACION_B1 SMALLINT,
		PRESION_LUBRICACION_B2 SMALLINT,
		PRESION_LUBRICACION_C1 SMALLINT,
		PRESION_LUBRICACION_C2 SMALLINT,
		TEMP_ROD_FRO_SUP_TX_SWING_2 SMALLINT,
		TEMP_ROD_POST_INF_TX_SWING_2 SMALLINT,
		TEMP_ROD_SUP_MOTOR_SWING_2 SMALLINT,
		TEMP_ROD_INF_TX_SWING_2 SMALLINT,
		BYTE_ESTATUS_1 TINYINT,
		BYTE_ESTATUS_2 TINYINT,
		BYTE_ESTATUS_3 TINYINT,
		BYTE_ESTATUS_4 TINYINT,
		BYTE_ESTATUS_5 TINYINT,
		BYTE_ESTATUS_6 TINYINT,
		BYTE_ESTATUS_HC_1 TINYINT,
		BYTE_ESTATUS_HC_2 TINYINT,
		BYTE_ESTATUS_HC_3 TINYINT,
		BYTE_ESTATUS_HC_4 TINYINT,
		HOROMETRO_MAQUINA INT,
		ID_OPERADOR VARCHAR(10),
		CONTEO_CICLOS INT,
		CONTEO_FALLAS_HOIST INT,
		CONTEO_FALLAS_CROWD INT,
		CONTEO_FALLAS_SWING INT,
		CONTEO_FALLAS_PROPEL INT,
		CONTEO_FALLAS_BOOM_JACK INT,
		CONTEO_FALLAS_AFE INT,
		TIEMPO_IDLE INT,
		TIEMPO_PROPEL INT,
		TIEMPO_DIG INT,
		TIEMPO_CICLO INT,
		CONTEO_NUEVO_CAMION INT,
		TIEMPO_NUEVO_CAMION INT,
		CONTADOR_PRESS_LUBE_A1 INT,
		CONTADOR_PRESS_LUBE_A2 INT,
		CONTADOR_PRESS_LUBE_B1 INT,
		CONTADOR_PRESS_LUBE_B2 INT,
		CONTADOR_PRESS_LUBE_C1 INT,
		CONTADOR_PRESS_LUBE_C2 INT,
		TIEMPO_CICLO_LUBE_A1 INT,
		TIEMPO_CICLO_LUBE_A2 INT,
		TIEMPO_CICLO_LUBE_B1 INT,
		TIEMPO_CICLO_LUBE_B2 INT,
		TIEMPO_CICLO_LUBE_C1 INT,
		TIEMPO_CICLO_LUBE_C2 INT,
		CROWD_STOP_LIMIT_EXTENSION INT,
		RET_STOP_LIMIT_EXTENSION INT,
		HOIST_STOP_LIMIT_EXTENSION INT,
		LOWER_STOP_LIMIT_EXTENSION INT,
		BOOM_JACK_FAULT_EXTENSION INT,
		SPARE_1 NUMERIC(12,8),
		SPARE_2 NUMERIC(12,8),
		SPARE_3 NUMERIC(12,8),
		SPARE_4 NUMERIC(12,8),
		SPARE_5 NUMERIC(12,8),
		SPARE_6 NUMERIC(12,8),
		SPARE_7 NUMERIC(12,8),
		SPARE_8 NUMERIC(12,8)
	);
	
IF OBJECT_ID('dbo.EQUIPO_PESADO') IS NULL
	CREATE TABLE dbo.EQUIPO_PESADO
	(
		EQUIPO_PESADO_ID VARCHAR(256) PRIMARY KEY,
		TIPO VARCHAR(32) NOT NULL,
		DESCRIPCION VARCHAR(1024) NOT NULL,
		ESTADO VARCHAR(32) NOT NULL,
		REPORTE VARCHAR(MAX) NOT NULL
	);

IF OBJECT_ID('dbo.EQUIPO_PESADO') IS NULL
	CREATE TABLE dbo.EQUIPO_PESADO
	(
		EQUIPO_PESADO_ID VARCHAR(256) PRIMARY KEY,
		TIPO VARCHAR(32) NOT NULL,
		DESCRIPCION VARCHAR(1024) NOT NULL,
		ESTADO VARCHAR(32) NOT NULL,
		REPORTE VARCHAR(MAX) NOT NULL
	);

IF OBJECT_ID('dbo.REGISTRO_ENTRADA') IS NULL
	CREATE TABLE dbo.REGISTRO_ENTRADA
	(
		ID BIGINT PRIMARY KEY IDENTITY,
		EQUIPO_PESADO_ID VARCHAR(256) NOT NULL,
		FECHA_HORA DATETIME NOT NULL,
		REGISTRO VARCHAR(1024) NOT NULL,
		FOREIGN KEY(EQUIPO_PESADO_ID) REFERENCES dbo.EQUIPO_PESADO(EQUIPO_PESADO_ID) 
	);

IF OBJECT_ID('dbo.CICLO') IS NULL
	CREATE TABLE dbo.CICLO
	(
		CICLO_ID BIGINT PRIMARY KEY IDENTITY,
		EQUIPO_PESADO_ID VARCHAR(256) NOT NULL,
		INICIO DATETIME NULL,
		FIN DATETIME NULL,
		ESTADO VARCHAR(32) NOT NULL, 
		FOREIGN KEY(EQUIPO_PESADO_ID) REFERENCES dbo.EQUIPO_PESADO(EQUIPO_PESADO_ID)
	);

IF OBJECT_ID('dbo.PROCESADO') IS NULL
	CREATE TABLE dbo.PROCESADO
	(
		CICLO_ID BIGINT NOT NULL,
		ORDEN INT NOT NULL,
		CARACTERISTICAS VARCHAR(1024) NOT NULL,
		CLASE INT NULL,
		PRIMARY KEY(CICLO_ID, ORDEN),
		FOREIGN KEY(CICLO_ID) REFERENCES dbo.CICLO(CICLO_ID)
	)

IF OBJECT_ID('dbo.CICLO_DETALLE') IS NULL
	CREATE TABLE dbo.CICLO_DETALLE
	(
		CICLO_ID bigint NOT NULL,
		ORDEN int NOT NULL,
		REGISTRO varchar(1024) NOT NULL,
		PRIMARY KEY(CICLO_ID, ORDEN),
		FOREIGN KEY(CICLO_ID) REFERENCES dbo.CICLO(CICLO_ID)
	)

GO