USE [RUL-WRS]
GO

IF OBJECT_ID('dbo.SELECCIONAR_EQUIPO_PESADO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SELECCIONAR_EQUIPO_PESADO
GO

CREATE PROCEDURE dbo.SELECCIONAR_EQUIPO_PESADO
AS 
   SELECT	EQUIPO_PESADO_ID,
			TIPO,
			DESCRIPCION,
			ESTADO,
			REPORTE
	FROM	dbo.EQUIPO_PESADO
	ORDER BY EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.CAMBIAR_ESTADO_EQUIPO_PESADO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.CAMBIAR_ESTADO_EQUIPO_PESADO
GO

CREATE PROCEDURE dbo.CAMBIAR_ESTADO_EQUIPO_PESADO
	@EQUIPO_PESADO_ID AS INT,
	@ESTADO	AS VARCHAR(32)
AS 
	UPDATE dbo.EQUIPO_PESADO
	SET	ESTADO = @ESTADO
	WHERE EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.SELECCIONAR_REGISTRO_ENTRADA', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SELECCIONAR_REGISTRO_ENTRADA
GO

CREATE PROCEDURE dbo.SELECCIONAR_REGISTRO_ENTRADA
	@EQUIPO_PESADO_ID AS INT
AS 
	SELECT	ID,
			EQUIPO_PESADO_ID,
			FECHA_HORA,
			REGISTRO
	FROM	dbo.REGISTRO_ENTRADA
	WHERE	EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.CREAR_CICLO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.CREAR_CICLO
GO

CREATE PROCEDURE dbo.CREAR_CICLO
	@EQUIPO_PESADO_ID AS INT,
	@ESTADO AS VARCHAR(32)
AS 
	-- Cerrar los otros ciclos
	INSERT INTO dbo.CICLO(EQUIPO_PESADO_ID, ESTADO) 
	VALUES(@EQUIPO_PESADO_ID, @ESTADO)
GO