use [RUL-WRS]
go

IF OBJECT_ID('dbo.EQUIPO_PESADO_SELECT') IS NULL
EXEC('CREATE PROCEDURE dbo.EQUIPO_PESADO_SELECT AS SET NOCOUNT ON;')
GO

ALTER PROCEDURE dbo.EQUIPO_PESADO_SELECT
AS 
   SELECT	EQUIPO_PESADO_ID,
			TIPO,
			DESCRIPCION,
			ESTADO,
			REPORTE
	FROM	EQUIPO_PESADO
	ORDER BY EQUIPO_PESADO_ID