USE [RUL-WRS]
GO

IF OBJECT_ID('dbo.SELECCIONAR_EQUIPO_PESADO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SELECCIONAR_EQUIPO_PESADO
GO

CREATE PROCEDURE dbo.SELECCIONAR_EQUIPO_PESADO
AS 
   SELECT	EQUIPO_PESADO_ID,
			TIPO,
			DESCRIPCION,
			ESTADO,
			REPORTE
	FROM	dbo.EQUIPO_PESADO
	ORDER BY EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.GUARDAR_EQUIPO_PESADO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.GUARDAR_EQUIPO_PESADO
GO

CREATE PROCEDURE dbo.GUARDAR_EQUIPO_PESADO
	@EQUIPO_PESADO_ID AS VARCHAR(256),
	@TIPO AS VARCHAR(32),
	@DESCRIPCION AS VARCHAR(1024),
	@ESTADO	AS VARCHAR(32),
	@REPORTE AS VARCHAR(MAX)
AS
	DECLARE @EXISTE AS BIT

	SELECT @EXISTE = COUNT(*) 
	FROM EQUIPO_PESADO
	WHERE EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID

	IF @EXISTE = 0
		INSERT INTO EQUIPO_PESADO(EQUIPO_PESADO_ID, TIPO, DESCRIPCION, ESTADO, REPORTE)
		VALUES(@EQUIPO_PESADO_ID, @TIPO, @DESCRIPCION, @ESTADO, @REPORTE)
	ELSE
		UPDATE EQUIPO_PESADO
		SET
			TIPO = @TIPO,
			DESCRIPCION = @DESCRIPCION,
			ESTADO = @ESTADO,
			REPORTE = @REPORTE
		WHERE EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID
GO
IF OBJECT_ID('dbo.SELECCIONAR_REGISTRO_ENTRADA', 'P') IS NOT NULL
	DROP PROCEDURE dbo.SELECCIONAR_REGISTRO_ENTRADA
GO

CREATE PROCEDURE dbo.SELECCIONAR_REGISTRO_ENTRADA
	@EQUIPO_PESADO_ID AS VARCHAR(256)
AS 
	SELECT	ID,
			EQUIPO_PESADO_ID,
			FECHA_HORA,
			REGISTRO
	FROM	dbo.REGISTRO_ENTRADA
	WHERE	EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.CREAR_CICLO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.CREAR_CICLO
GO

CREATE PROCEDURE dbo.CREAR_CICLO
	@EQUIPO_PESADO_ID AS VARCHAR(256),
	@INICIO AS DATETIME,
	@FIN AS DATETIME,
	@ESTADO AS VARCHAR(32)
AS 
	-- Crear nuevo ciclo
	INSERT INTO dbo.CICLO(EQUIPO_PESADO_ID, INICIO, FIN, ESTADO) 
	VALUES(@EQUIPO_PESADO_ID, @INICIO, @FIN, @ESTADO)

	COMMIT
GO

IF OBJECT_ID('dbo.LEER_ULTIMO_CICLO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.LEER_ULTIMO_CICLO
GO

-- TODO ADD EQUIPO_PESADO_ID AS PARAMETER
CREATE PROCEDURE dbo.LEER_ULTIMO_CICLO
AS 
	SELECT	CICLO_ID,
			EQUIPO_PESADO_ID,
			INICIO,
			FIN,
			ESTADO
	FROM	CICLO
	WHERE	CICLO_ID = (SELECT MAX(CICLO_ID) FROM dbo.CICLO)
GO

<<<<<<< Updated upstream
=======
IF OBJECT_ID('dbo.INFORMACION_CICLOS_POR_EQUIPO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.INFORMACION_CICLOS_POR_EQUIPO
GO

CREATE PROCEDURE dbo.INFORMACION_CICLOS_POR_EQUIPO
	@EQUIPO_PESADO_ID AS VARCHAR(256)
AS 
	SELECT	COUNT(*) AS CANTIDAD_CICLOS
	FROM	CICLO
	WHERE	EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID
GO

IF OBJECT_ID('dbo.CREAR_CICLO_DETALLE', 'P') IS NOT NULL
	DROP PROCEDURE dbo.CREAR_CICLO_DETALLE
GO

CREATE PROCEDURE dbo.CREAR_CICLO_DETALLE
	@CICLO_ID AS BIGINT,
	@ETAPA AS VARCHAR(32),
	@REGISTRO_ENTRADA_ID AS BIGINT
AS 
	DECLARE @REGISTRO VARCHAR(1024)
	
	SELECT	@REGISTRO = REGISTRO
	FROM	REGISTRO_ENTRADA
	WHERE	ID = @REGISTRO_ENTRADA_ID

	BEGIN TRANSACTION;  

		INSERT INTO dbo.CICLO_DETALLE(CICLO_ID, ID, REGISTRO, ETAPA) 
		VALUES(@CICLO_ID, @REGISTRO_ENTRADA_ID, @REGISTRO, @ETAPA)

		DELETE	REGISTRO_ENTRADA
		WHERE	ID = @REGISTRO_ENTRADA_ID

	COMMIT;
GO

IF OBJECT_ID('dbo.BORRAR_REGISTROS_FUERA_DE_CICLO', 'P') IS NOT NULL
	DROP PROCEDURE dbo.BORRAR_REGISTROS_FUERA_DE_CICLO
GO

CREATE PROCEDURE dbo.BORRAR_REGISTROS_FUERA_DE_CICLO
	@EQUIPO_PESADO_ID AS VARCHAR(256),
	@CICLO_ID AS BIGINT,
	@REGISTRO_ENTRADA_ID AS BIGINT
AS 
	DELETE	REGISTRO_ENTRADA
	WHERE	EQUIPO_PESADO_ID = @EQUIPO_PESADO_ID AND
			ID < @REGISTRO_ENTRADA_ID
	COMMIT
GO


>>>>>>> Stashed changes
IF OBJECT_ID('dbo.GUARDAR_CARACTERISTICAS', 'P') IS NOT NULL
	DROP PROCEDURE dbo.GUARDAR_CARACTERISTICAS
GO

CREATE PROCEDURE dbo.GUARDAR_CARACTERISTICAS
	@CICLO_ID AS INT,
	@CARACTERISTICAS AS VARCHAR(1024),
	@ETAPA AS VARCHAR(32)
AS 
	DECLARE @ORDEN AS INT
	SELECT @ORDEN = COUNT(*) + 1 FROM dbo.PROCESADO WHERE CICLO_ID = @CICLO_ID

	-- Guardar vector caracteristica
	INSERT INTO dbo.PROCESADO
	(
		CICLO_ID,
		ORDEN,
		CARACTERISTICAS,
		ETAPA
	)
	VALUES
	(
		@CICLO_ID,
		@ORDEN,
		@CARACTERISTICAS,
		@ETAPA
	);
GO

IF OBJECT_ID('dbo.LLENA_REGISTRO_ENTRADA') IS NOT NULL
	DROP TRIGGER dbo.LLENA_REGISTRO_ENTRADA
GO

CREATE TRIGGER dbo.LLENA_REGISTRO_ENTRADA  
ON dbo.IOT_GATEWAY  
AFTER INSERT   
AS  
	DECLARE @EQUIPO_PESADO_ID AS VARCHAR(256)
	DECLARE @FECHA_HORA AS DATETIME
	DECLARE @REGISTRO AS VARCHAR(4096)

	SELECT	@EQUIPO_PESADO_ID = i.MACHINE_IDENTIFIER,
			@FECHA_HORA = DATE_TIME,
			@REGISTRO = (
				SELECT	DATE_TIME,
						MACHINE_IDENTIFIER,
						TYPE_OF_MACHINE,
						DIPPER_LOAD, --CARGA_CUCHARON,
						HOIST_ROPE_LENGTH, --LONGITUD_CABLE_HOIST,
						HOIST_SPEED, --VELOCIDAD_HOIST,
						STATUS_BYTE_3, --BYTE_ESTATUS_3,
						HOIST_TORQUE, --TORQUE_HOIST,
						HOIST_IW, --CORRIENTE_IW_HOIST,
						HOIST_SPEED_REF, --VEL_REF_HOIST,
						CROWD_SPEED_REF, --VEL_REFERENCIA_CROWD,
						HOIST_KW, --POTENCIA_KW_HOIST,
						CROWD_EXTENSION, --EXTENSION_CROWD,
						SWING_ANGLE --ANGULO_SWING
				FROM INSERTED i
				FOR JSON PATH, Without_Array_Wrapper
			)
	FROM	INSERTED i
	
	INSERT INTO DBO.REGISTRO_ENTRADA
	(
		EQUIPO_PESADO_ID,
		FECHA_HORA,
		REGISTRO
	)
	VALUES
	(
		@EQUIPO_PESADO_ID,
		@FECHA_HORA,
		@REGISTRO
	);
GO
